const SHOP_DATA = [
  {
    title: "Womens",
    items: [
      {
        id: 1,
        name: "Blue Tanktop",
        desc: {
          color: "blue",
          style: "casual",
          composition: "100% cotton",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/7CQVJNm/blue-tank.png",
        price: 25,
      },
      {
        id: 2,
        name: "Floral Blouse",
        desc: {
          color: "various",
          style: "floral",
          composition: "polyester",
          pattern: "floral",
        },
        imageUrl: "https://i.ibb.co/4W2DGKm/floral-blouse.png",
        price: 20,
      },
      {
        id: 3,
        name: "Floral Dress",
        desc: {
          color: "various",
          style: "floral",
          composition: "polyester",
          pattern: "floral",
        },
        imageUrl: "https://i.ibb.co/KV18Ysr/floral-skirt.png",
        price: 80,
      },
      {
        id: 4,
        name: "Red Dots Dress",
        desc: {
          color: "red",
          style: "vintage",
          composition: "cotton",
          pattern: "polka dots",
        },
        imageUrl: "https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png",
        price: 80,
      },
      {
        id: 5,
        name: "Striped Sweater",
        desc: {
          color: "various",
          style: "casual",
          composition: "wool",
          pattern: "striped",
        },
        imageUrl: "https://i.ibb.co/KmSkMbH/striped-sweater.png",
        price: 45,
      },
      {
        id: 6,
        name: "Yellow Track Suit",
        desc: {
          color: "yellow",
          style: "sporty",
          composition: "polyester",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/v1cvwNf/yellow-track-suit.png",
        price: 135,
      },
      {
        id: 7,
        name: "White Blouse",
        desc: {
          color: "white",
          style: "casual",
          composition: "cotton",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/qBcrsJg/white-vest.png",
        price: 20,
      },
    ],
  },
  {
    title: "Mens",
    items: [
      {
        id: 8,
        name: "Camo Down Vest",
        desc: {
          color: "camo",
          style: "outdoor",
          composition: "polyester",
          pattern: "camouflage",
        },
        imageUrl: "https://i.ibb.co/xJS0T3Y/camo-vest.png",
        price: 325,
      },
      {
        id: 9,
        name: "Floral T-shirt",
        desc: {
          color: "various",
          style: "floral",
          composition: "cotton",
          pattern: "floral",
        },
        imageUrl: "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
        price: 20,
      },
      {
        id: 10,
        name: "Black & White Longsleeve",
        desc: {
          color: "black and white",
          style: "casual",
          composition: "cotton",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/55z32tw/long-sleeve.png",
        price: 25,
      },
      {
        id: 11,
        name: "Pink T-shirt",
        desc: {
          color: "pink",
          style: "casual",
          composition: "cotton",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/RvwnBL8/pink-shirt.png",
        price: 25,
      },
      {
        id: 12,
        name: "Jean Long Sleeve",
        desc: {
          color: "blue",
          style: "casual",
          composition: "denim",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
        price: 40,
      },
      {
        id: 13,
        name: "Burgundy T-shirt",
        desc: {
          color: "burgundy",
          style: "casual",
          composition: "cotton",
          pattern: "polka dots",
        },
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        price: 25,
      },
    ],
  },
  {
    title: "Accessories",
    items: [
      {
        id: 14,
        name: "Brown Brim",
        desc: {
          color: "brown",
          style: "casual",
          composition: "straw",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        price: 25,
      },
      {
        id: 15,
        name: "Blue Beanie",
        desc: {
          color: "blue",
          style: "casual",
          composition: "wool",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        price: 18,
      },
      {
        id: 16,
        name: "Brown Cowboy",
        desc: {
          color: "brown",
          style: "western",
          composition: "felt",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
        price: 35,
      },
      {
        id: 17,
        name: "Grey Brim",
        desc: {
          color: "grey",
          style: "casual",
          composition: "straw",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
        price: 25,
      },
      {
        id: 18,
        name: "Green Beanie",
        desc: {
          color: "green",
          style: "casual",
          composition: "wool",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/YTjW3vF/green-beanie.png",
        price: 18,
      },
      {
        id: 19,
        name: "Palm Tree Cap",
        desc: {
          color: "white",
          style: "casual",
          composition: "cotton",
          pattern: "palm trees",
        },
        imageUrl: "https://i.ibb.co/rKBDvJX/palm-tree-cap.png",
        price: 14,
      },
      {
        id: 20,
        name: "Red Beanie",
        desc: {
          color: "red",
          style: "casual",
          composition: "wool",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/bLB646Z/red-beanie.png",
        price: 18,
      },
      {
        id: 21,
        name: "Wolf Cap",
        desc: {
          color: "black",
          style: "casual",
          composition: "cotton",
          pattern: "wolf",
        },
        imageUrl: "https://i.ibb.co/1f2nWMM/wolf-cap.png",
        price: 14,
      },
      {
        id: 22,
        name: "Blue Snapback",
        desc: {
          color: "blue",
          style: "casual",
          composition: "cotton",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/X2VJP2W/blue-snapback.png",
        price: 16,
      },
    ],
  },
  {
    title: "Shoes",
    items: [
      {
        id: 23,
        name: "Adidas NMD",
        desc: {
          color: "black",
          style: "sporty",
          composition: "textile",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/0s3pdnc/adidas-nmd.png",
        price: 220,
      },
      {
        id: 24,
        name: "Adidas Yeezy",
        desc: {
          color: "grey",
          style: "sporty",
          composition: "textile",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/dJbG1cT/yeezy.png",
        price: 280,
      },
      {
        id: 25,
        name: "Black Converse",
        desc: {
          color: "black",
          style: "casual",
          composition: "canvas",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/bPmVXyP/black-converse.png",
        price: 110,
      },
      {
        id: 26,
        name: "Nike White AirForce",
        desc: {
          color: "white",
          style: "sporty",
          composition: "leather",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/1RcFPk0/white-nike-high-tops.png",
        price: 160,
      },
      {
        id: 27,
        name: "Nike Red High Tops",
        desc: {
          color: "red",
          style: "sporty",
          composition: "leather",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/QcvzydB/nikes-red.png",
        price: 160,
      },
      {
        id: 28,
        name: "Nike Brown High Tops",
        desc: {
          color: "brown",
          style: "sporty",
          composition: "leather",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/fMTV342/nike-brown.png",
        price: 160,
      },
      {
        id: 29,
        name: "Air Jordan Limited",
        desc: {
          color: "black",
          style: "sporty",
          composition: "leather",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/w4k6Ws9/nike-funky.png",
        price: 190,
      },
      {
        id: 30,
        name: "Timberlands",
        desc: {
          color: "brown",
          style: "outdoor",
          composition: "leather",
          pattern: "plain",
        },
        imageUrl: "https://i.ibb.co/Mhh6wBg/timberlands.png",
        price: 200,
      },
    ],
  },
  {
    title: "Kids",
    items: [
      {
        id: 31,
        name: "Orange Pants",
        imageUrl:
          "https://images.pexels.com/photos/1619772/pexels-photo-1619772.jpeg?auto=compress&cs=tinysrgb&w=1600",
        price: 25,
        desc: {
          color: "orange",
          style: "casual",
          composition: "100% cotton",
          pattern: "plain",
        },
      },
      {
        id: 32,
        name: "Green Floral Dress",
        imageUrl:
          "https://images.pexels.com/photos/1133721/pexels-photo-1133721.jpeg?auto=compress&cs=tinysrgb&w=1600",
        price: 40,
        desc: {
          color: "green",
          style: "floral",
          composition: "100% polyester",
          pattern: "floral",
        },
      },
      {
        id: 33,
        name: "Long Sleeves T-shirt",
        imageUrl:
          "https://images.pexels.com/photos/1620769/pexels-photo-1620769.jpeg?auto=compress&cs=tinysrgb&w=1600",
        price: 15,
        desc: {
          color: "various",
          style: "casual",
          composition: "100% cotton",
          pattern: "solid",
        },
      },
      {
        id: 34,
        name: "Owl Beanie",
        imageUrl:
          "https://images.pexels.com/photos/459957/pexels-photo-459957.jpeg?auto=compress&cs=tinysrgb&w=1600",
        price: 10,
        desc: {
          color: "brown",
          style: "beanie",
          composition: "100% acrylic",
          pattern: "animal",
        },
      },
      {
        id: 35,
        name: "Potato Halloween Set",
        imageUrl:
          "https://images.pexels.com/photos/6334321/pexels-photo-6334321.jpeg?auto=compress&cs=tinysrgb&w=1600",
        price: 100,
        desc: {
          color: "orange",
          style: "costume",
          composition: "polyester",
          pattern: "Halloween",
        },
      },
    ],
  },
];

export default SHOP_DATA;
